//--------VARIABLE ARE 3 TYPES//
//1. VAR, 2.LET, 3.CONST

//VAR: VAR DIYE VARIABLE DECALRE KORLE WINDOW TE ADD HOI
//     VAR HOCHE FUNCTION SCOPE
//     RE-DECLARE AND RE-ASSIGN KORA JAI
//     HOISTING TO TOP WITH UNDEFINED VALUE

//LET: LET HOCHE BLOCK SCOPE
//     RE-ASSIGN KORA JAI KINTU RE-DECLARE KORA JAI NA
//     TDZ(TEMPORAL DEAD ZONE) APPLIES HERE

//CONST: CONST HOCHE BLOCK SCOPE
//       RE-ASSIGN AND RE-DECLARE DUTOI KORA JAINA
//       AKHANEO TDZ APPLIES HOCHE





//-------TDZ 1 THEKE 5 PROJONTO TEMPORAL DEAD ZONE
// JS JANE JANE JE VARIABLE ACHE KINTU VALUE DITE PARENA //

// console.log(c);

// let c = 15;

//-----HOISTING//

// var a = undefined;

// console.log(a);

// a = 25;

//------ VAR JODI CURLY BRACESER VITORE THAKE AR KONO ROKOM FUNCTION-ER VITORE THAKE NA//
//TAHOLEO SETA GLOBAL SCOPE//

// var x = 1;  // global scope //
// {
//     var x = 3;//eitao global scope//
// }
// console.log(x);

// ------LET KEYWORDS CURLY BRACES-ER RESPECT KORE

// let a = 10;//global scope//
// {
//     let a = 20;//block scope//
//     console.log("inside", a);
// }
// console.log("outside", a);


//-------VAR DIYE VARIABLE BANALE FUNCTION SCOPE HOI, KARON VAR KEYWORDS SUDHU FUNCTION SCOPE-ER RESPECT KORE BAAKI//
//IF OR FOR KE KONO RESPECT KORE NA//



